set-option -g prefix C-s
set-option buffer-limit 1000
set-option -g history-limit 100000
set-option -g default-terminal xterm-256color
set -g status-interval 2
set -g base-index 1
set -sg escape-time 0
bind h set -g status
bind-key j command-prompt -p "send pane to:"  "join-pane -t '%%'"
bind-key e select-layout even-vertical
bind-key E select-layout even-horizontal
bind-key X setw synchronize-panes
set-window-option -g mode-keys vi
bind + copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle
bind m \
  set -g mouse on \;\
  display 'Mouse: ON'
bind M \
  set -g mouse off \;\
  display 'Mouse: OFF'
bind C send-keys "clear" c-m \; run-shell "sleep .3s" \; clear-history
source-file $HOME/.tmux-style.conf

set-option -g status-position top

#set -g status off
